# Imports

 Cover fundamentals of tensors using TensorFlow.
 
- Introduction to tensors
- Getting information from tensors
- Manipulating tensors
- Tensors and NumPy
- Using @tf.function (a way to speed up python)
- Using GPUs with TensorFlow (or TPUs)
- Exercises to try for yourself


## Introduction to Tensors

In [4]:
import pandas as pd
import tensorflow as tf
import numpy as np
import tensorflow_hub as hub

In [3]:
print(tf.__version__)

2.14.0


In [6]:
# Creating Tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [7]:
# Check number of dimensions of tensor, ndim
scalar.ndim

0

In [8]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [9]:
vector.ndim

1

In [12]:
# create a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [14]:
matrix.ndim

2

In [22]:
# create another matrix 
another_matrix = tf.constant([[[10.,7.],
                              [3.,2.]],
                              [[8.,9.],
                              [6.,2.]]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(2, 2, 2), dtype=float16, numpy=
array([[[10.,  7.],
        [ 3.,  2.]],

       [[ 8.,  9.],
        [ 6.,  2.]]], dtype=float16)>

In [23]:
another_matrix.ndim

3

In [24]:
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [25]:
tensor.ndim

3

What we've created so far:
- scalar : single number
- vector: a number with direction
- matrix: 2-dimensional array of numbers
- tensor: n-dimensional array of numbers

### Creating tesnors with tf.Variable

In [27]:
variable = tf.Variable([1.,2.,3.])
variable

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>